/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIMessage: typeof import('./components/MessageView/AIMessage.vue')['default']
    ChatView: typeof import('./components/ChatView.vue')['default']
    HumanMessage: typeof import('./components/MessageView/HumanMessage.vue')['default']
    MessageView: typeof import('./components/MessageView/index.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    PromptBox: typeof import('./components/PromptBox.vue')['default']
  }
}
